name: Scrape MALEE with Gemini

on:
  workflow_dispatch:
  # จ.-ศ. ช่วง 09:00–16:00 ICT (02:00–09:59 UTC) ทุก 30 นาที
  schedule:
    - cron: "*/30 2-9 * * 1-5"

concurrency:
  group: scrape-malee
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Export CHROME_PATH for Selenium
        run: echo "CHROME_PATH=${{ steps.chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      # 🔧 ลบ chromedriver เก่าที่ติดมากับ image เพื่อให้ Selenium Manager เลือกเวอร์ชันที่ถูกต้องเอง
      - name: Remove system chromedriver in PATH
        run: |
          sudo rm -f /usr/bin/chromedriver || true
          sudo apt-get remove -y chromium-chromedriver || true

      # (debug) แสดงเวอร์ชัน Chrome / เช็คว่ามี chromedriver ค้างไหม
      - name: Show Chrome / chromedriver versions
        run: |
          echo "Chrome at: $CHROME_PATH"
          "$CHROME_PATH" --version || true
          which chromedriver || echo "chromedriver not present (good)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper_ai_malee.py

      - name: Upload artifact (price.json)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: malee-price
          path: price.json
          if-no-files-found: ignore

      - name: Commit JSON to repo (optional)
        if: ${{ success() && hashFiles('price.json') != '' }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p data
          cp price.json "data/price_$(date -u +'%Y%m%dT%H%M%SZ').json"
          git add price.json data/
          git commit -m "Update MALEE price.json [skip ci]" || echo "Nothing to commit"
          git pull --rebase --autostash || true
          git push || true

          name: or-diesel-prices
          path: or_diesel_prices.json
          if-no-files-found: ignore
